---
- name: install mytop
  yum: name=mytop state=present

- name: install git
  yum: name=git state=present

- name: checkout mysqlreport
  git: repo=https://github.com/daniel-nichter/hackmysql.com.git dest=/root/mysqlreport accept_hostkey=true
